export enum AnalyticsCategoryVars {
  USER_ENGAGEMENT = 'USER_ENGAGEMENT',
  SESSION = 'SESSION',
  EVENT_TYPE = 'EVENT_TYPE',
}

export enum AnalyticsCommandVars {
  AVERAGE_EVENTS_PER_USER = 'AVERAGE_EVENTS_PER_USER',
  TOTAL_EVENTS_PER_USER = 'TOTAL_EVENTS_PER_USER',
  ACTIVE_USERS = 'ACTIVE_USERS',
  SESSIONS_PER_USER = 'SESSIONS_PER_USER',
  SESSIONS_PER_TIME_PERIOD = 'SESSIONS_PER_TIME_PERIOD',
  EVENT_TYPE_DISTRIBUTION = 'EVENT_TYPE_DISTRIBUTION',
  COMMON_EVENT_TYPES = 'COMMON_EVENT_TYPES',
  EVENTS_BY_EVENT_AND_USER = 'EVENTS_BY_EVENT_AND_USER',
}
